# route registerAction
front_register:
    path:     /register
    defaults: { _controller: AppBundle:User/Security:register }

# route loginAction
front_login:
    path:     /login
    defaults: { _controller: AppBundle:User/Security:login }

# route logoutAction
logout:
    path:     /logout
    defaults: { _controller: AppBundle:User/Security:logout }

# pageBlogParDefault
front_index:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:index }

# route search
front_search:
    path:     /search
    defaults: { _controller: AppBundle:Front/Front:search }

# route faq
front_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Front/Front:faq }

# route articleAction
front_article_show:
    path:     /article/{articleId}
    defaults: { _controller: AppBundle:Front/Article:show }

# route CategoryAction
front_category_show:
    path:     /category/{categoryId}
    defaults: { _controller: AppBundle:Front/Category:show }

# route contactAction
front_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Front/Front:contact }

# interfaceAdmin
back_index:
    path:     /admin
    defaults: { _controller: AppBundle:Back/Back:index }

# route BackindexContactAction
back_contact_index:
    path:     /admin/contact
    defaults: { _controller: AppBundle:Back/Contact:index }

# route viewAction
back_contact_show:
    path:     /contact/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:show }

# route updateAction
back_contact_update:
    path:     /update/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:update }

# route deleteAction
back_contact_delete:
    path:     /delete/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:delete }

# AdminCategoryIndex
back_category_index:
    path:    /admin/category
    defaults: { _controller: AppBundle:Back/Category:index }

# AdminCategoryNew
back_category_new:
    path:    /admin/category/new
    defaults: { _controller: AppBundle:Back/Category:new }

# AdminCategoryShow
back_category_show:
    path:    /admin/category/show/{categoryId}
    defaults: { _controller: AppBundle:Back/Category:show }

# AdminBlog
back_article_index:
    path:     /admin/articles
    defaults: { _controller: AppBundle:Back/Article:index }

# AdminBlogNew
back_article_new:
    path:     /admin/article/new
    defaults: { _controller: AppBundle:Back/Article:new }

# route showActionArticleAdmin
back_article_show:
    path:     /admin/article/{articleId}
    defaults: { _controller: AppBundle:Back/Article:show }

# route updateActionArticleAdmin
back_article_update:
    path:     /admin/article/update/{articleId}
    defaults: { _controller: AppBundle:Back/Article:update }

# route updateActiveAction
back_article_update_active:
    path:     /admin/article/update/active/{articleId}
    defaults: { _controller: AppBundle:Back/Article:updateActive }

# route updateActionCommentAdmin
back_comment_show:
    path:     /admin/comment/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:show }

# route updateActionCommentAdmin
back_comment_update:
    path:     /admin/comment/update/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:update }

# route users back
back_user_index:
    path:     /admin/users
    defaults: { _controller: AppBundle:Back/User:index }

# route show user back
back_user_show:
    path:     /admin/user/{userId}
    defaults: { _controller: AppBundle:Back/User:show }

# route user update back
back_user_update:
    path:     /admin/update/{userId}
    defaults: { _controller: AppBundle:Back/User:update }

# route user update back
back_user_delete:
    path:     /admin/delete/{userId}
    defaults: { _controller: AppBundle:Back/User:delete }

# route roles back
back_role_index:
    path:     /admin/roles
    defaults: { _controller: AppBundle:Back/Role:index }

# route new role back
back_role_new:
    path:     /admin/role/new
    defaults: { _controller: AppBundle:Back/Role:new }

# route update role back
back_role_update:
    path:     /admin/role/update/{roleId}
    defaults: { _controller: AppBundle:Back/Role:update }
