# pageBlogParDefault
front_index:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:index }

# route search
front_search:
    path:     /search
    defaults: { _controller: AppBundle:Front/Front:search }

# route faq
front_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Front/Front:faq }

# route articleAction
front_article_show:
    path:     /article/{articleId}
    defaults: { _controller: AppBundle:Front/Article:show }

# route CategoryAction
front_category_show:
    path:     /category/{categoryId}
    defaults: { _controller: AppBundle:Front/Category:show }

# route contactAction
front_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Front/Front:contact }

# route registerAction
front_register:
    path:     /register
    defaults: { _controller: AppBundle:Front/Register:register }

# interfaceAdmin
back_index:
    path:     /admin
    defaults: { _controller: AppBundle:Back/Back:index }

# route BackindexContactAction
back_contact_index:
    path:     /admin/contact
    defaults: { _controller: AppBundle:Back/Contact:index }

# route viewAction
back_contact_show:
    path:     /contact/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:show }

# route updateAction
back_contact_update:
    path:     /update/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:update }

# route deleteAction
back_contact_delete:
    path:     /delete/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:delete }

# AdminCategoryIndex
back_category_index:
    path:    /admin/category
    defaults: { _controller: AppBundle:Back/Category:index }

# AdminCategoryNew
back_category_new:
    path:    /admin/category/new
    defaults: { _controller: AppBundle:Back/Category:new }

# AdminBlog
back_article_index:
    path:     /admin/articles
    defaults: { _controller: AppBundle:Back/Article:index }

# AdminBlogNew
back_article_new:
    path:     /admin/article/new
    defaults: { _controller: AppBundle:Back/Article:new }

# route showActionArticleAdmin
back_article_show:
    path:     /admin/article/{articleId}
    defaults: { _controller: AppBundle:Back/Article:show }

# route updateActionArticleAdmin
back_article_update:
    path:     /admin/article/update/{articleId}
    defaults: { _controller: AppBundle:Back/Article:update }

# route updateActionCommentAdmin
back_comment_show:
    path:     /admin/comment/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:show }

# route updateActionCommentAdmin
back_comment_update:
    path:     /admin/comment/update/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:update }