#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation

# app/config/routing.yml
front_index:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:index }
#route faq
front_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Front/Front:faq }
#route contactAction
front_contact_form:
    path:     /contact
    defaults: { _controller: AppBundle:Front/Contact:contact }
#route listAction
front_contact_list:
    path:     /list
    defaults: { _controller: AppBundle:Back/Contact:list }
#route viewAction
front_contact_show:
    path:     /show/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:show }
#route updateAction
front_contact_update:
    path:     /update/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:update }