#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation
# app/config/routing.yml
#pageBlogParDefault
front_index:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:index }
#route faq
front_faq:
    path:     /faq
    defaults: { _controller: AppBundle:Front/Front:faq }
#route articleAction
front_article_show:
    path:     /article/{articleId}
    defaults: { _controller: AppBundle:Front/Article:show }
#route contactAction
front_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Front/Front:contact }
#route listAction
back_contact_list:
    path:     /list
    defaults: { _controller: AppBundle:Back/Contact:list }
#route viewAction
back_contact_show:
    path:     /contact/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:show }
#route updateAction
back_contact_update:
    path:     /update/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:update }
#route deleteAction
back_contact_delete:
    path:     /delete/{contactId}
    defaults: { _controller: AppBundle:Back/Contact:delete }
##########################################################################
#interfaceAdmin
back_index:
    path:     /admin
    defaults: { _controller: AppBundle:Back/Back:index }
#AdminBlog
back_article_index:
    path:     /admin/articles
    defaults: { _controller: AppBundle:Back/Article:index }
#route showActionArticleAdmin
back_article_show:
    path:     /admin/article/{articleId}
    defaults: { _controller: AppBundle:Back/Article:show }
#route updateActionArticleAdmin
back_article_update:
    path:     /admin/article/update/{articleId}
    defaults: { _controller: AppBundle:Back/Article:update }
#route updateActionCommentAdmin
back_comment_show:
    path:     /admin/comment/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:show }
#route updateActionCommentAdmin
back_comment_update:
    path:     /admin/comment/update/{commentId}
    defaults: { _controller: AppBundle:Back/Comment:update }
##########################################################################