#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation

# app/config/routing.yml
front_index:
    path:     /
    defaults: { _controller: AppBundle:Front/Front:index }
#commentaire
front_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Front/Front:contact }