security:
    providers:
        sf_blog:
            entity:
                class:    AppBundle:User\User
                property: username

    encoders:
        AppBundle\Entity\User\User:
            algorithm: bcrypt
            cost     : 15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        back:
            anonymous: ~
            logout:
                path:   logout
                target: /login
            guard:
                authenticators:
                    - AppBundle\Security\Guard\Authenticator\FormAuthenticator

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: ROLE_USER }
