<?php

namespace AppBundle\Entity\Article\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTerm($term)
    {
        $queryBuilder = $this->createQueryBuilder('a')
            ->where('a.content = :term')
            ->setParameter(':term', $term);

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}