<?php

namespace AppBundle\Entity\Article\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $term
     * @param null $limit
     * @return array
     */
    public function findByTerm($term, $limit = null)
    {
        $queryBuilder = $this
        	->createQueryBuilder('co')
            ->where('co.content LIKE :term')
            ->setParameter(':term', '%' . $term . '%');

        if ($limit) {
            $queryBuilder->setMaxResults($limit);
        }

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $article
     * @return array
     */
    public function findByArtilcle($article)
    {
        $queryBuilder = $this
            ->createQueryBuilder('co')
            ->where('co.article = :article')
            ->setParameter(':article', $article);

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}